package de.wursteintopf.bot.utils;

public enum State {
    ADMIN_LOADUSER,  ADMIN_UNBLOCKUSER,  ADMIN_ADDCHATCATEGORY,  ADMIN_ADDCHATUID,  ADMIN_ADDCHATNAME,  ADMIN_ADDCHATURL,  ADMIN_EDITCHAT,  ADMIN_CHANGECHATUID,  ADMIN_CHANGECHATNAME,  ADMIN_CHANGECHATURL
}
